### ISSUE TITLE
TODOとやったこと

### ISSUE THREAD

**Issue by shun91** [shun91/nuxt-express-typescript-template#1]
## TODO

- [ ] cross-envいらないのでは？
- [ ] git commit 時の lint 実行
- [ ] eslint 設定 (セミコロン必須とか)
- [ ] src ディレクトリ作成
- [ ] @nuxtjs/vuetify に置き換え
- [ ] vue ファイルのパッケージ化
- [ ] typescript 化
  - [ ] lint 導入
- [ ] serverMiddleware
- [ ] jest周り (yarn test ではカバレッジ出さないとか)
- [ ] stylelint 導入
- [ ] サーバーサイドに nestjs 入れてみる

## やったこと

プロジェクト作成

```
$ yarn create nuxt-app nuxt-express-typescript-template

? Project name nuxt-express-typescript-template
? Project description My rad Nuxt.js project
? Use a custom server framework none
? Choose features to install Linter / Formatter, Prettier, Axios
? Use a custom UI framework vuetify
? Use a custom test framework jest
? Choose rendering mode Universal
? Author name shun91
? Choose a package manager yarn
```

この時点で以下は設定済み

- vuetify tree-shaking 有効化

eslint-loader削除 e76a7b5 4e74d66

```
yarn remove eslint-loader
```
